# Generated by Django 2.2.6 on 2020-01-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess',
            name='to',
            field=models.BigIntegerField(),
        ),
    ]
