# Generated by Django 2.2.6 on 2019-10-24 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
