# Generated by Django 2.2.6 on 2019-10-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_status_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='like',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
