# Generated by Django 2.2.6 on 2019-10-26 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_userlogin_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='img',
            new_name='imgage',
        ),
    ]
