# Generated by Django 2.2.6 on 2019-10-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_uploadpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='image',
            field=models.ImageField(blank=True, default='user.png', upload_to=''),
        ),
    ]
