# Generated by Django 2.2.6 on 2019-11-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20191104_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(default='', max_length=50),
        ),
    ]
