# Generated by Django 2.2.6 on 2019-11-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20191104_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
