# Generated by Django 2.2.6 on 2019-11-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_education_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
