# Generated by Django 2.2.6 on 2019-11-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20191104_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='departmentName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='leavingDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
