# Generated by Django 2.2.6 on 2020-01-11 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('comment', models.CharField(max_length=2000)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Status')),
            ],
        ),
    ]
