# Generated by Django 2.2.6 on 2020-01-14 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20200111_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
