# Generated by Django 2.2.6 on 2020-01-14 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_comments_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Status')),
            ],
        ),
    ]
