# Generated by Django 2.2.6 on 2020-01-27 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_statuslike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userlogin',
        ),
    ]
